# Generated by Django 4.2.18 on 2025-02-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_cidade"),
    ]

    operations = [
        migrations.CreateModel(
            name="pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=100)),
                ("data_nascimento", models.DateField(max_length=100)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="alunos.cidade"
                    ),
                ),
            ],
        ),
    ]
